const allLeagues = [
  { name: "English Premier League", id: 47, table: "english_premier_league" },
  { name: "La liga", id: 87, table: "la_liga" },
  { name: "Seria A", id: 55, table: "seria_a" },
  { name: "Bundesliga", id: 54, table: "bundesliga" },
  { name: "Ligue 1", id: 53, table: "ligue_1" },
  { name: "Liga Profesional", id: 112, table: "liga_profesional" },
  { name: "Austrian Bundesliga", id: 38, table: "austrian_bundesliga" },
  { name: "Belgian Pro League", id: 40, table: "belgian_pro_league" },
  { name: "Brazilian Serie A", id: 268, table: "brazilian_serie_a" },
  {
    name: "Croatian Football League",
    id: 252,
    table: "croatian_football_league",
  },
  { name: "Czech First League", id: 122, table: "czech_first_league" },
  { name: "Danish League", id: 46, table: "danish_league" },
  { name: "Championship", id: 48, table: "championship" },
  { name: "LaLiga 2", id: 140, table: "laliga_2" },
  { name: "2. Bundesliga", id: 146, table: "bundesliga_2" },
  { name: "Irish Premier Division", id: 126, table: "irish_premier_division" },
  { name: "Italian Serie B", id: 86, table: "italian_serie_b" },
  {
    name: "Saudi Arabian Pro League",
    id: 536,
    table: "saudi_arabian_pro_league",
  },
  { name: "Mexican Liga MX", id: 230, table: "mexican_liga_mx" },
  { name: "Eredivise", id: 57, table: "eredivise" },
  { name: "Norway Elite Serien", id: 59, table: "norway_elite_serien" },
  { name: "Polish Ekstraklasa", id: 196, table: "polish_ekstraklasa" },
  { name: "Liga Portugal", id: 61, table: "liga_portugal" },
  { name: "Russian Premier League", id: 63, table: "russian_premier_league" },
  { name: "Scotish Premiership", id: 64, table: "scottish_premiership" },
  {
    name: "Switzerland Super League",
    id: 69,
    table: "switzerland_super_league",
  },
  { name: "Swedish Allsvenskan", id: 67, table: "swedish_allsvenskan" },
  { name: "Turkish Super Lig", id: 71, table: "turkish_super_lig" },
  { name: "MLS", id: 130, table: "mls" },
];

module.exports = allLeagues;
